### ISSUE TITLE
WillPopeScope is now deprecated. I tried using PopScope since your approach isn't working now.  Below is the error I'm getting. 

### ISSUE THREAD

**Issue by sistercharmings777** [academind/flutter-complete-guide-course-resources#18]
Restarted application in 670ms.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5238 pos 12: '!_debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5238:12)
#3      _FiltersScreenState.build.<anonymous closure> (package:meals/screens/filters.dart:43:35)
#4      ModalRoute.onPopInvoked (package:flutter/src/widgets/routes.dart:1574:30)
#5      _RouteEntry.pop (package:flutter/src/widgets/navigator.dart:3083:11)
#6      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5251:13)
#7      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5204:9)
<asynchronous suspension>

**Comment by jose-guevarra** [comment]
Try something like this:

screens/tabs.dart
==========

  void _setScreen(String identifier) async {
    Navigator.of(context).pop();
    if (identifier == 'filters') {
      final result = await Navigator.of(context).push<Map<Filter, bool>>(
        MaterialPageRoute(
          builder: (ctx) => FiltersScreen(currentFilters: _selectedFilters),
        ),
      );
      setState(() {
        _selectedFilters = result ?? kInitialFilters; // checks if null then
      });
    }
  }

==========

screens/filters.dart
==========

      body: PopScope(
        canPop: false,
        onPopInvokedWithResult: (bool didPop, dynamic result) {
          if (didPop) return;
          Navigator.of(context).pop({
            Filter.glutenFree: _glutenFreeFilterSet,
            Filter.lactoseFree: _lactoseFreeFilterSet,
            Filter.vegetarian: _vegetarianFilterSet,
            Filter.vegan: _veganFilterSet,
          });
        },
       
==========


for later versions of API(> 34?) you may need to update android/app/src/main/AndroidManifest.xml. Add this to the manifest -> application section

android:enableOnBackInvokedCallback="true"
